# Women Accessing Financial Accounts

Over time, women have increasingly gained access to financial accounts. This project will explore whether specific Latin American countries have followed this global trend and examine how their progress compares to wider international patterns.

In [ ]:
#First dataset, findex from World Bank
import pandas as pd

url_findex = "/Users/anamontanez/Documents/Anana2314.github.io/PROJECT 1/GlobalFindexDatabase2025.csv"
df = pd.read_csv(url_findex)
df.head()

/var/folders/ky/p2ghgwb15rq__jgw7h54ck140000gn/T/ipykernel_92369/3885664492.py:4: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url_findex)

,countrynewwb,codewb,year,pop_adult,regionwb24_hi,incomegroupwb24,group,group2,account_t_d,fiaccount_t_d,...,con12m_s,con26lm_s,con12w_s,con2f_s,con13_s,con26m_s,con28lm_s,con5a_s,con17c_s,con32h_s
0,Afghanistan,AFG,2011,14575546.0,South Asia (excluding high income),Low income,all,all,0.090050,0.090050,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Albania,ALB,2011,2281010.0,Europe & Central Asia (excluding high income),Upper middle income,all,all,0.282681,0.282681,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Algeria,DZA,2011,26251587.0,Middle East & North Africa (excluding high inc...,Lower middle income,all,all,0.332861,0.332861,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Angola,AGO,2011,12779501.0,Sub-Saharan Africa (excluding high income),Lower middle income,all,all,0.392035,0.392035,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Argentina,ARG,2011,30685516.0,Latin America & Caribbean (excluding high income),Upper middle income,all,all,0.331302,0.331302,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#  This dataset have % female population per country (World Bank) 
# because many of the columns at the Findex are percentages but we can't know 
# the number of women to make further comparisions.

url_female = "/Users/anamontanez/Documents/Anana2314.github.io/PROJECT2/Population, female (% of total population).csv"
female_pct = pd.read_csv(url_female)

female_pct.rename(columns={
    "Country Name": "countrynewwb",
    "Year": "year",
    "Value": "pct_female"
}, inplace=True)

In [28]:
female_pct.head(5)

,Indicator Name,Indicator Code,countrynewwb,Country Code,year,pct_female,Disaggregation
0,"Population, female (% of total population)",SP.POP.TOTL.FE.ZS,Africa Eastern and Southern,AFE,2024,50.496,NaN
1,"Population, female (% of total population)",SP.POP.TOTL.FE.ZS,Africa Eastern and Southern,AFE,2023,50.503,NaN
2,"Population, female (% of total population)",SP.POP.TOTL.FE.ZS,Africa Eastern and Southern,AFE,2022,50.512,NaN
3,"Population, female (% of total population)",SP.POP.TOTL.FE.ZS,Africa Eastern and Southern,AFE,2021,50.519,NaN
4,"Population, female (% of total population)",SP.POP.TOTL.FE.ZS,Africa Eastern and Southern,AFE,2020,50.525,NaN

As a first step it's necessary to merge both datasets because the findex does not have female population information, it only has adult population per country but we need to see how many women have an account and beyond that, how many of them use their bank account and/or have savings.

Also, the WB dataset only has % of women population per country but not the number of women per country.

In [30]:
merged = pd.merge(
    df,
    female_pct[["countrynewwb", "year", "pct_female"]],
    on=["countrynewwb", "year"],
    how="left"
)

In [31]:
merged[["countrynewwb", "year", "pop_adult", "pct_female"]].head()

  countrynewwb  year   pop_adult  pct_female
0  Afghanistan  2011  14575546.0      49.518
1      Albania  2011   2281010.0      50.510
2      Algeria  2011  26251587.0      48.746
3       Angola  2011  12779501.0      50.678
4    Argentina  2011  30685516.0      50.560

In [ ]:
#To create the column of n female adult population per country

merged["adult_pop_female"] = merged["pop_adult"] * merged["pct_female"] / 100

merged[["countrynewwb", "year", "pop_adult", "pct_female", "adult_pop_female"]].head()

  countrynewwb  year   pop_adult  pct_female  adult_pop_female
0  Afghanistan  2011  14575546.0      49.518      7.217519e+06
1      Albania  2011   2281010.0      50.510      1.152138e+06
2      Algeria  2011  26251587.0      48.746      1.279660e+07
3       Angola  2011  12779501.0      50.678      6.476396e+06
4    Argentina  2011  30685516.0      50.560      1.551460e+07

In [33]:
merged.columns.tolist()

['countrynewwb',
 'codewb',
 'year',
 'pop_adult',
 'regionwb24_hi',
 'incomegroupwb24',
 'group',
 'group2',
 'account_t_d',
 'fiaccount_t_d',
 'mobileaccount_t_d',
 'borrow_any_t_d',
 'fin4_d',
 'dig_acc',
 'fin11_2a',
 'fin11a',
 'fin11b',
 'fin11c',
 'fin11f',
 'fin11d',
 'fin11e',
 'fin14a',
 'fin14b',
 'fin14c',
 'fin14d',
 'fin13_1a',
 'fin13_1b',
 'fin26a',
 'fin26b',
 'fin27a',
 'fin27b',
 'fin17f',
 'fin17a_17a1_d',
 'fin17a',
 'fin17b',
 'fin17c',
 'fin22d',
 'fin22e',
 'fin22a_22a1_22g_d',
 'fin22a',
 'fin22a_1',
 'fin22b',
 'fin22c',
 'fin24sav',
 'fin24fam',
 'fin24work',
 'fin24bor',
 'fin24sell',
 'fin24other',
 'fin24aVD',
 'fin24aSD',
 'fin24aND',
 'fin24aSD_ND',
 'fin24aP',
 'fin24aN',
 'fin24sav_SD_ND',
 'fin24fam_SD_ND',
 'fin24work_SD_ND',
 'fin24bor_SD_ND',
 'fin24sell_SD_ND',
 'fin24other_SD_ND',
 'fin24sav_VD',
 'fin24fam_VD',
 'fin24work_VD',
 'fin24bor_VD',
 'fin24sell_VD',
 'fin24other_VD',
 'fh1',
 'fin28',
 'fh2',
 'fin29',
 'fin31a_31b',
 'fin30',
 'fin31a',
 'fin31b',
 'fin31d',
 'fin32_33_34a',
 'fin32_33_34b',
 'fin32_33_34c',
 'fin32_33_34d',
 'fin32_33_acc',
 'fin32_33',
 'fin32_n33_34a',
 'fin32_n33_34b',
 'fin32_n33_34c',
 'fin32_n33_34d',
 'fin32_n33_acc',
 'fin32_n33',
 'fin32',
 'fin32_acc',
 'fin34a',
 'fin34b',
 'fin34c',
 'fin34d',
 'fin37_38_39a',
 'fin37_38_39b',
 'fin37_38_39c',
 'fin37_38_39d',
 'fin37_38_39_acc',
 'fin37_38',
 'fin37_39a',
 'fin37_39b',
 'fin37_39c',
 'fin37_39d',
 'fin37_39_acc',
 'fin37',
 'fin38_39a',
 'fin38_39b',
 'fin38_39c',
 'fin38_39d',
 'fin38_39_acc',
 'fin38',
 'fin2_t_d',
 'fin42',
 'fin42_acc',
 'fin43a',
 'fin43b',
 'fin43c',
 'fin43d',
 'fin45a',
 'fin45c',
 'fin45d',
 'fin45e',
 'fin45b',
 'fin25e2',
 'fin9b',
 'fin10',
 'fin22g',
 'fin22h',
 'inactive_t_d',
 'fing2p_acc',
 'fing2p_card',
 'fing2p_cash',
 'fing2p_fin',
 'fing2p_mob',
 'fing2p',
 'g20_made',
 'g20_received',
 'g20_any',
 'merchant_pay',
 'save_any_t_d',
 'fin11_1',
 'fin5w',
 'fin5m',
 'fin5lm',
 'fin5n',
 'fin6w',
 'fin6m',
 'fin6lm',
 'fin6n',
 'fin11_0',
 'fin9a',
 'fin17dw',
 'fin17dm',
 'fin17dlm',
 'fin17e',
 'fin7',
 'fin3',
 'fin19',
 'fin20',
 'fin21',
 'fin24ba',
 'fin24bb',
 'fin24bc',
 'fin24bd',
 'fin24c',
 'fin24d1',
 'fin24d2',
 'fin24d3',
 'fin25e1',
 'fin25e2b',
 'fin25e3w',
 'fin25e3m',
 'fin25e3lm',
 'fin25e4a',
 'fin25e4b',
 'fin25e4c',
 'fin25e4d',
 'fin25e4e',
 'fh2a',
 'fin31c',
 'fin36a',
 'fin36b',
 'fin40a',
 'fin40b',
 'fin36Aa',
 'fin36Ab',
 'fin8',
 'fin13aw',
 'fin13am',
 'fin13alm',
 'fin13an',
 'fin13bw',
 'fin13bm',
 'fin13blm',
 'fin13bn',
 'fin13cw',
 'fin13cm',
 'fin13clm',
 'fin13cn',
 'fin13e',
 'fin13f',
 'fin13f_1',
 'fin15',
 'fin16',
 'fin22f',
 'fin41',
 'fin35',
 'fin44',
 'fh1_fh2',
 'fin28_29',
 'fin31d_s',
 'fin32_n33_34c_s',
 'fin34c_s',
 'fin43c_s',
 'fin32_acc_s',
 'fin34a_s',
 'fin32_33_acc_s',
 'inactive_t_d_s',
 'fing2p_fin_s',
 'fin32_33_34a_s',
 'fin32_n33_acc_s',
 'fin37_39_acc_s',
 'fin37_39c_s',
 'fin31a_31b_s',
 'fin31a_s',
 'fin31b_s',
 'fin32_n33_34a_s',
 'fin37_39a_s',
 'fin34d_s',
 'fin32_33_34d_s',
 'fin32_n33_34d_s',
 'fing2p_card_s',
 'fin37_39d_s',
 'fin42_acc_s',
 'fin32_33_34c_s',
 'fin37_38_39c_s',
 'fin38_39c_s',
 'fing2p_acc_s',
 'fing2p_cash_s',
 'fin37_38_39a_s',
 'fin37_38_39_acc_s',
 'fin38_39a_s',
 'fin38_39_acc_s',
 'fin34b_s',
 'fin32_n33_34b_s',
 'fin43b_s',
 'fin27b_s',
 'fin27a_s',
 'fin22h_s',
 'fin28_29_s',
 'fin28_s',
 'fin29_s',
 'fing2p_mob_s',
 'fin37_38_39d_s',
 'fin37_38_39b_s',
 'fin37_39b_s',
 'fin11_2a_s',
 'fin11b_s',
 'fin11f_s',
 'fin11d_s',
 'fin11e_s',
 'fin9b_s',
 'fin11_1_s',
 'fin5m_s',
 'fin6m_s',
 'fin9a_s',
 'fin5w_s',
 'fin6w_s',
 'fin17dm_s',
 'fin17dlm_s',
 'fin25e3w_s',
 'fin25e3m_s',
 'fin24d1_s',
 'fin14d_s',
 'fin24d2_s',
 'fin11a_s',
 'fin11c_s',
 'fin5lm_s',
 'fin6lm_s',
 'fin17dw_s',
 'fin14c_s',
 'fin13_1a_s',
 'fin13_1b_s',
 'fin13am_s',
 'fin13alm_s',
 'fin13bm_s',
 'fin13blm_s',
 'fin13cm_s',
 'fin13clm_s',
 'fin21_s',
 'fin14b_s',
 'fin13cw_s',
 'fin13f_s',
 'fin14a_s',
 'fin25e3lm_s',
 'fin13aw_s',
 'fin13bw_s',
 'fin24d3_s',
 'fin5n_s',
 'fin6n_s',
 'fin13f_1_s',
 'fin32_33_34b_s',
 'con1',
 'con2a',
 'con2b',
 'con2c',
 'con2d',
 'con2e',
 'con2f',
 'con2g',
 'con3a',
 'con3b',
 'con3c',
 'con3d',
 'con3e',
 'con3f',
 'con3g',
 'con4',
 'con5a',
 'con5b',
 'con6',
 'con7',
 'con8',
 'con9a',
 'con9b',
 'con10',
 'con11',
 'con12d',
 'con12w',
 'con12m',
 'con12lm',
 'con13',
 'con14',
 'con15',
 'con16',
 'con17a',
 'con17b',
 'con17c',
 'con17d',
 'con18',
 'con19',
 'con20',
 'con21',
 'con22',
 'con23',
 'internet',
 'con26d',
 'con26w',
 'con26m',
 'con26lm',
 'con27',
 'con28d',
 'con28w',
 'con28m',
 'con28lm',
 'con28n',
 'con29',
 'con30a',
 'con30b',
 'con30c',
 'con30d',
 'con30e',
 'con30f',
 'con30g',
 'con30h',
 'con31a',
 'con31b',
 'con31c',
 'con31d',
 'con31e',
 'con31f',
 'con31g',
 'con31h',
 'con32a',
 'con32b',
 'con32c',
 'con32d',
 'con32e',
 'con32f',
 'con32g',
 'con32h',
 'con10_s',
 'con11_s',
 'con12d_s',
 'con14_s',
 'con16_s',
 'con17a_s',
 'con17b_s',
 'con18_s',
 'con19_s',
 'con20_s',
 'con21_s',
 'con26d_s',
 'con27_s',
 'con28m_s',
 'con30a_s',
 'con30b_s',
 'con30c_s',
 'con30d_s',
 'con30e_s',
 'con30f_s',
 'con30g_s',
 'con30h_s',
 'con31a_s',
 'con31b_s',
 'con31f_s',
 'con2a_s',
 'con15_s',
 'con17d_s',
 'con29_s',
 'con31d_s',
 'con31h_s',
 'con32a_s',
 'con3a_s',
 'con4_s',
 'con28d_s',
 'con28w_s',
 'con23_s',
 'con31c_s',
 'con2b_s',
 'con2d_s',
 'con26w_s',
 'con2c_s',
 'con2e_s',
 'con2g_s',
 'con5b_s',
 'con12m_s',
 'con26lm_s',
 'con12w_s',
 'con2f_s',
 'con13_s',
 'con26m_s',
 'con28lm_s',
 'con5a_s',
 'con17c_s',
 'con32h_s',
 'pct_female',
 'adult_pop_female']

In [ ]:
#We will first calculate how many women have an account 
#The variable to use according to their dictionary is 'account_t_d'
#Checking we have all the columns
merged.columns

Index(['countrynewwb', 'codewb', 'year', 'pop_adult', 'regionwb24_hi',
       'incomegroupwb24', 'group', 'group2', 'account_t_d', 'fiaccount_t_d',
       ...
       'con12w_s', 'con2f_s', 'con13_s', 'con26m_s', 'con28lm_s', 'con5a_s',
       'con17c_s', 'con32h_s', 'pct_female', 'adult_pop_female'],
      dtype='object', length=439)

In [ ]:
#Filtering women 
women = merged[(merged["group"] == "gender") & (merged["group2"] == "women")].copy()
men    = merged[(merged["group"] == "gender") & (merged["group2"] == "men")].copy()

In [85]:
women.head()
women.columns

Index(['countrynewwb', 'codewb', 'year', 'pop_adult', 'regionwb24_hi',
       'incomegroupwb24', 'group', 'group2', 'account_t_d', 'fiaccount_t_d',
       ...
       'con2f_s', 'con13_s', 'con26m_s', 'con28lm_s', 'con5a_s', 'con17c_s',
       'con32h_s', 'pct_female', 'adult_pop_female', 'adult_pop_male'],
      dtype='object', length=440)

In [ ]:
#Now we create women with account

women["women_with_account"] = women["adult_pop_female"] * women["account_t_d"]

In [87]:
women[["countrynewwb","year","adult_pop_female","account_t_d","women_with_account"]].head()

    countrynewwb  year  adult_pop_female  account_t_d  women_with_account
712      Albania  2011      1.152138e+06     0.226726        2.612198e+05
714      Algeria  2011      1.279660e+07     0.204073        2.611440e+06
716       Angola  2011      6.476396e+06     0.389283        2.521154e+06
718    Argentina  2011      1.551460e+07     0.318186        4.936522e+06
720      Armenia  2011      1.330127e+06     0.181486        2.413990e+05

In [ ]:
#Filter only since 2014
women = women[women["year"] >= 2014]

In [ ]:
#We choose three countries 
target_countries = ["Argentina", "Mexico", "Colombia"]

women = women[women["countrynewwb"].isin(target_countries)]

In [103]:
women[["countrynewwb","year","adult_pop_female","account_t_d","women_with_account"]].head()

     countrynewwb  year  adult_pop_female  account_t_d  women_with_account
974     Argentina  2014      1.608941e+07     0.508524        8.181846e+06
1024     Colombia  2014      1.734356e+07     0.339537        5.888772e+06
1134       Mexico  2014      4.319722e+07     0.388982        1.680294e+07
1256    Argentina  2017      1.666074e+07     0.507573        8.456532e+06
1302     Colombia  2017      1.825338e+07     0.424744        7.753021e+06

In [ ]:
countries = ["Argentina", "Mexico", "Colombia"]
women_sub = women[women["countrynewwb"].isin(countries)].copy()

In [109]:
import plotly.express as px

fig = px.line(
    women_sub,
    x="year",
    y="women_with_account",
    color="countrynewwb",
    title="Women with Bank Accounts Over Time",
    markers=True
)

fig.update_layout(
    title={
        "text": "Women with Bank Accounts Over Time",
        "x": 0.5,      
        "xanchor": "center"
    },
    xaxis_title="Year",
    yaxis_title="Women with Account"
)

fig.show()

# Conclusion

Mexico is the country with the most sustained growth in the number of women with a bank account. After a slight drop in 2017, it shows a consistent increase from 2017 to 2024, with the most pronounced rise occurring between 2021 and 2024.

Argentina also shows a growing trend starting in 2017, although the pace of growth is more moderate than in Mexico. Even thought, it maintains a continuous increase over the years.

Colombia shows growth between 2014 and 2021, but unlike the other two countries, it experiences a decrease between 2021 and 2024, breaking the previous upward trend.